// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_Apli1_Lohammy.DAL;

#nullable disable

namespace P2_Apli1_Lohammy.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            ComponenteId = 1,
                            Descripcion = "Memoria 4GB",
                            Existencia = 1,
                            Precio = 1580m
                        },
                        new
                        {
                            ComponenteId = 2,
                            Descripcion = "Disco SSD 120MB",
                            Existencia = 8,
                            Precio = 4200m
                        },
                        new
                        {
                            ComponenteId = 3,
                            Descripcion = "Tarjeta de Video",
                            Existencia = 4,
                            Precio = 10000m
                        });
                });

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.RegistroPedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.ToTable("RegistroPedidos");
                });

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.RegistroPedidosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("PedidoId");

                    b.ToTable("RegistroPedidosDetalle");
                });

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.RegistroPedidosDetalle", b =>
                {
                    b.HasOne("P2_Apli1_Lohammy.Models.Componente", "Componentes")
                        .WithMany("PedidosDetalles")
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_Apli1_Lohammy.Models.RegistroPedidos", "RegistroPedido")
                        .WithMany("PedidosDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componentes");

                    b.Navigation("RegistroPedido");
                });

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.Componente", b =>
                {
                    b.Navigation("PedidosDetalles");
                });

            modelBuilder.Entity("P2_Apli1_Lohammy.Models.RegistroPedidos", b =>
                {
                    b.Navigation("PedidosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
